### ISSUE TITLE
[Discussion] dtplyr dependency

### ISSUE THREAD

**Issue by artemklevtsov** [hrbrmstr/ndjson#1]
Hi.

What is reason to use the `dtplyr` package in `Imports`? Really needed only `data.table::rbindlist`.
Let's see a `dtplyr` dependencies:

```r
R> miniCRAN::pkgDep("dtplyr", availPkgs = available.packages(), suggests = FALSE)
 [1] "dtplyr"     "dplyr"      "data.table" "lazyeval"   "assertthat" "R6"         "Rcpp"       "tibble"    
 [9] "magrittr"   "DBI"        "BH"
```

but `data.table` haven't any dependncies.

In fact `dtplyr::tbl_dt` only sets `c("tbl_dt", "tbl", "data.table", "data.frame")` as `class` attribute.

**Comment by hrbrmstr** [comment]
I despise data.table hieroglyphs syntax (they are the antithesis of
literate programming) and hold out hope that various volunteers will take
up the maintenance of the dtplyr pkg. I'm also a fan of the tidyverse and
those pkgs come for the ride there. It is open source so you are free to
fork and do what you like. The next CRAN release will also enable selecting
between returning a tbl_dt or tbl_df so said dependencies aren't going away
anyway.
